import type { UserConfigType } from "@/types";
import {
  blueSkyIcon,
  facebookIcon,
  githubIcon,
  instagramIcon,
  linkedinIcon,
  mastodonIcon,
  snapchatIcon,
  telegramIcon,
  threadsIcon,
  whatsappIcon,
  xIcon,
  youtubeIcon,
} from "@/assets";

const userConfig: UserConfigType = {
  avatarSrc: "/assets/avatar.webp",
  avatarAlt: "Avatar",
  fullName: "Linkfolio",
  alias: "demo",
  metaTitle: "Linkfolio",
  metaDescription: "A Hub for all your online links 🔗",
  enableTypingAlias: false,
  darkTheme: {
    "color-primary": "oklch(0.82 0.04 160)",
    "color-secondary": "oklch(0.72 0.06 160)",
    "color-background-start": "oklch(0.17 0.02 160)",
    "color-background-end": "oklch(0.19 0.02 155)",
    "lf-card-bg": "oklch(0.23 0.03 160)",
    "lf-card-shadow": "0 4px 24px -6px oklch(0 0 0 / 0.3)",
    "lf-card-border": "1px solid oklch(0.82 0.04 160 / 0.06)",
    "lf-name-color": "oklch(0.90 0.03 160)",
    "lf-alias-color": "oklch(0.72 0.06 160)",
    "lf-network-hover-bg": "oklch(0.82 0.04 160 / 0.05)",
    "lf-description-color": "oklch(0.70 0.04 160)",
  },
  socialNetworks: [
    {
      url: "#1",
      iconSrc: xIcon,
      title: "Twitter / X",
      description: "🐦 Thoughts in 280 chars",
    },
    {
      url: "#2",
      iconSrc: githubIcon,
      title: "GitHub",
      description: "💻 Code & Collaborate",
    },
    {
      url: "#3",
      iconSrc: linkedinIcon,
      title: "LinkedIn",
      description: "🤝 Professional Network",
    },
    {
      url: "#4",
      iconSrc: facebookIcon,
      title: "Facebook",
      description: "👥 Friends & Updates",
    },
    {
      url: "#5",
      iconSrc: instagramIcon,
      title: "Instagram",
      description: "📸 Life in Pictures",
    },
    {
      url: "#6",
      iconSrc: snapchatIcon,
      title: "Snapchat",
      description: "👻 Fleeting Moments",
    },
    {
      url: "#7",
      iconSrc: whatsappIcon,
      title: "WhatsApp",
      description: "💬 Instant Chats",
    },
    {
      url: "#8",
      iconSrc: telegramIcon,
      title: "Telegram",
      description: "🚀 Swift & Secure",
    },
    {
      url: "#9",
      iconSrc: youtubeIcon,
      title: "YouTube",
      description: "🎥 Watch & Create",
    },
    {
      url: "#10",
      iconSrc: threadsIcon,
      title: "Threads",
      description: "🧵 Short Updates",
    },
    {
      url: "#11",
      iconSrc: blueSkyIcon,
      title: "BlueSky",
      description: "🌤️ Open Social Web",
    },
    {
      url: "#12",
      iconSrc: mastodonIcon,
      title: "Mastodon",
      description: "🐘 Decentralized Social",
      group: "socialnetwork",
    },
    {
      url: "#13",
      iconSrc: "/assets/banner-portfolio.png",
      title: "Portfolio",
      description: "Design work and case studies",
      group: "website",
    },
    {
      url: "#14",
      iconSrc: "/assets/banner-cooking.png",
      title: "Cooking Channel",
      description: "Weekly recipes from around the world",
      group: "website",
    },
    {
      url: "#15",
      iconSrc: "/assets/banner-notepad.png",
      title: "Notepad",
      description: "Offline-first markdown note-taking app",
      group: "project",
    },
    {
      url: "#16",
      iconSrc: "/assets/banner-mood.png",
      title: "Mood Tracker",
      description: "Daily mood logging with charts and insights",
      group: "project",
    },
    {
      url: "#17",
      iconSrc: "/assets/banner-splitbill.png",
      title: "Split Bill",
      description: "Expense splitting for groups and roommates",
      group: "project",
    },
  ],
};

export default userConfig;
