import {
  blueSkyIcon,
  facebookIcon,
  githubIcon,
  instagramIcon,
  linkedinIcon,
  mastodonIcon,
  snapchatIcon,
  telegramIcon,
  threadsIcon,
  whatsappIcon,
  xIcon,
  youtubeIcon,
} from "./assets";
import { UserConfigType } from "./types";

const defaultConfig: UserConfigType = {
  socialNetworks: [
    {
      url: "#",
      iconSrc: xIcon,
      title: "Twitter / X",
      description: "#DevLife #CodeNewbie 🐦",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: githubIcon,
      title: "GitHub",
      description: "Versioning my projects 📁",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: linkedinIcon,
      title: "LinkedIn",
      description: "Building my professional network. Let's connect! 🌐",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: facebookIcon,
      title: "Facebook",
      description: "Sharing life's highlights 🌟🤝",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: instagramIcon,
      title: "Instagram",
      description: "Capturing life's frames 📷",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: snapchatIcon,
      title: "Snapchat",
      description: "Capturing daily moments 📸",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: whatsappIcon,
      title: "WhatsApp",
      description: "Simple, reliable messaging and calling 🟢",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: telegramIcon,
      title: "Telegram",
      description: "Messaging focusing on speed and security 🚀",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: youtubeIcon,
      title: "YouTube",
      description: "Discover, watch, and share your passion 🎥",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: mastodonIcon,
      title: "Mastodon",
      description: "Sharing without the mainstream noise 🐘",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: blueSkyIcon,
      title: "BlueSky",
      description: "Exploring open social web 💙",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: threadsIcon,
      title: "Threads",
      description: "Quick updates and stories! 🌀",
      group: "socialnetwork",
    },
    {
      url: "#",
      iconSrc: githubIcon,
      title: "My Blog",
      description: "Thoughts on code, design, and open source",
      group: "website",
    },
    {
      url: "#",
      iconSrc: githubIcon,
      title: "Weather App",
      description: "A minimal weather dashboard built with React",
      group: "project",
    },
    {
      url: "#",
      iconSrc: githubIcon,
      title: "Task Tracker",
      description: "Kanban-style project management tool",
      group: "project",
    },
    {
      url: "#",
      iconSrc: githubIcon,
      title: "Pixel Art Editor",
      description: "Create and share pixel art in the browser",
      group: "project",
    },
  ],
};

export default defaultConfig;
