name: Next

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: vue
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint
      - uses: cypress-io/github-action@v5
        with:
          working-directory: packages/front
          build: pnpm run build
          start: pnpm run dev
